/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KaramellGlass (https://sketchfab.com/KaramellGlass)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desk-lamp-7377ec591df04445a1aae370017aaa13
Title: Desk lamp
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import IntrinsicElements = React.JSX.IntrinsicElements;

type GLTFResult = GLTF & {
  nodes: {
    ['Cylinder001_04_-_Default_0']: THREE.Mesh
    ['Cylinder003_04_-_Default_0']: THREE.Mesh
    ['Box009_01_-_Default_0']: THREE.Mesh
    ['Cylinder004_04_-_Default_0']: THREE.Mesh
    ['Cylinder005_01_-_Default_0']: THREE.Mesh
    ['Cylinder005_Material_#13_0']: THREE.Mesh
    ['Cylinder006_01_-_Default_0']: THREE.Mesh
    ['Sphere001_03_-_Default_0']: THREE.Mesh
    ['Object003_01_-_Default_0']: THREE.Mesh
    ['Object004_01_-_Default_0']: THREE.Mesh
    ['Object006_01_-_Default_0']: THREE.Mesh
    ['Spring013_02_-_Default_0']: THREE.Mesh
    ['Object008_04_-_Default_0']: THREE.Mesh
    ['Object012_04_-_Default_0']: THREE.Mesh
    ['Object013_03_-_Default_0']: THREE.Mesh
    ['Object014_04_-_Default_0']: THREE.Mesh
    ['Sphere017_03_-_Default_0']: THREE.Mesh
    ['Cylinder008_04_-_Default_0']: THREE.Mesh
    ['Object015_04_-_Default_0']: THREE.Mesh
    ['Box010_04_-_Default_0']: THREE.Mesh
    ['Object016_04_-_Default_0']: THREE.Mesh
    ['Line002_04_-_Default_0']: THREE.Mesh
    ['Object017_04_-_Default_0']: THREE.Mesh
    ['Object018_01_-_Default_0']: THREE.Mesh
    ['Object019_04_-_Default_0']: THREE.Mesh
    ['Object020_04_-_Default_0']: THREE.Mesh
    ['Object021_04_-_Default_0']: THREE.Mesh
    ['Sphere020_05_-_Default_0']: THREE.Mesh
    Sphere020_Ceramic_0: THREE.Mesh
    ['Box011_03_-_Default_0']: THREE.Mesh
  }
  materials: {
    ['04_-_Default']: THREE.MeshStandardMaterial
    ['01_-_Default']: THREE.MeshStandardMaterial
    Material_13: THREE.MeshStandardMaterial
    ['03_-_Default']: THREE.MeshStandardMaterial
    ['02_-_Default']: THREE.MeshStandardMaterial
    ['05_-_Default']: THREE.MeshStandardMaterial
    Ceramic: THREE.MeshStandardMaterial
  }
}

export function DeskLampModel(props: IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/desklamp.opt.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.0592}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-4.98602, 32.56076, 0]} rotation={[Math.PI, 0, 2.45473]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Box009_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
              position={[0, 0, -0.76176]}
            />
          </group>
          <group position={[8.67178, 0.16269, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Cylinder005_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Cylinder005_Material_#13_0'].geometry}
              material={materials.Material_13}
            />
          </group>
          <group position={[-13.34323, 26.48254, 0]} rotation={[-Math.PI, 0, -1.82567]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object003_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
              position={[0.08908, 1.0441, -1]}
            />
          </group>
          <group position={[-14.04836, 26.06568, 0]} rotation={[-Math.PI, 0, -1.82567]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object004_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
              position={[0.08908, 1.0441, -1]}
            />
          </group>
          <group position={[-14.04836, 26.06568, 0]} rotation={[-Math.PI, 0, -1.82567]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object006_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
              position={[0.08908, 1.0441, -1]}
            />
          </group>
          <group position={[-13.48524, 26.5573, 0]} rotation={[-Math.PI, 0, -1.82567]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object008_04_-_Default_0'].geometry}
              material={materials['04_-_Default']}
              position={[0.08908, 1.0441, -1]}
            />
          </group>
          <group position={[-4.98602, 32.56076, 0]} rotation={[Math.PI, 0, 2.45473]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object017_04_-_Default_0'].geometry}
              material={materials['04_-_Default']}
              position={[0, 0, -0.76176]}
            />
          </group>
          <group position={[-15.81055, 26.05281, 0]} rotation={[Math.PI, 0, 2.45473]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object018_01_-_Default_0'].geometry}
              material={materials['01_-_Default']}
              position={[-12.49675, -1.83174, -0.76176]}
            />
          </group>
          <group position={[-9.13347, 7.29096, 0]} rotation={[-Math.PI, 0, -0.67816]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object019_04_-_Default_0'].geometry}
              material={materials['04_-_Default']}
              position={[-12.49675, -1.83174, -0.76176]}
            />
          </group>
          <group position={[-13.48524, 26.5573, 0]} rotation={[-Math.PI, 0, -1.82567]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Object021_04_-_Default_0'].geometry}
              material={materials['04_-_Default']}
              position={[0.08908, 1.0441, -1]}
            />
          </group>
          <group position={[8.64951, 29.39972, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Sphere020_05_-_Default_0'].geometry}
              material={materials['05_-_Default']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sphere020_Ceramic_0.geometry}
              material={materials.Ceramic}
            />
            <spotLight
              position={[0, -0, 0]}
              target-position={[0, -1, 0.3]}
              color="#ffd9a0"
              intensity={2.5}
              angle={0.5}
              penumbra={0.6}
              decay={2}
              distance={1.5}
              castShadow
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cylinder001_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[-3.39287, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cylinder003_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[-7.97027, 2.98008, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cylinder004_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[1.84103, 36.84857, 0]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cylinder006_01_-_Default_0'].geometry}
            material={materials['01_-_Default']}
            position={[-3.39287, 1, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Sphere001_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
            position={[-8.38519, 6.91793, -0.68278]}
            rotation={[Math.PI, 0, -Math.PI]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Spring013_02_-_Default_0'].geometry}
            material={materials['02_-_Default']}
            position={[-4.84497, 9.15596, -1.75389]}
            rotation={[0, 0, 1.85039]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object012_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[-8.07985, 2.39163, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object013_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
            position={[-8.12439, 2.39163, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object014_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[8.67178, 0.48975, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Sphere017_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
            position={[5.84106, 36.88049, -0.66741]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Cylinder008_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[2.42318, 37.54667, -4.6782]}
            rotation={[Math.PI, 0, -2.79253]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object015_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[2.51916, 35.88348, 8.4289]}
            scale={[-1, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Box010_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[1.87773, 36.06131, 1.63917]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object016_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[1.87773, 36.06131, 1.63917]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Line002_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[-13.68363, 28.67301, 0]}
            rotation={[Math.PI, 0, -Math.PI]}
            scale={[1, 1, 1.24134]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object020_04_-_Default_0'].geometry}
            material={materials['04_-_Default']}
            position={[5.84106, 36.88049, -0.66741]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Box011_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
            position={[19.79643, 0, 4.39612]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/desklamp.opt.glb')
