/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Giora (https://sketchfab.com/ChubbyPanda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monstera-deliciosa-potted-mid-century-plant-1ab9bf841df04c07b1819be596327629
Title: Monstera Deliciosa Potted Mid-Century plant
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import IntrinsicElements = React.JSX.IntrinsicElements;

type GLTFResult = GLTF & {
  nodes: {
    root_HP_1_Mat2_0: THREE.Mesh
    Leaves_Mat1_0: THREE.Mesh
    Stand_Mat_0: THREE.Mesh
    Pot_LP_Mat_0: THREE.Mesh
  }
  materials: {
    ['Mat.2']: THREE.MeshStandardMaterial
    ['Mat.1']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
  }
}

export function HousePlant(props: IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/houseplant.opt.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.8635}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.root_HP_1_Mat2_0.geometry}
            material={materials['Mat.2']}
            position={[0.071, 0.0602, 0.2193]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Leaves_Mat1_0.geometry}
            material={materials['Mat.1']}
            position={[4.6065, 54.241, -4.8952]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Stand_Mat_0.geometry}
            material={materials.material}
            position={[0, 2.4549, 7.5852]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Pot_LP_Mat_0.geometry}
            material={materials.material}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/houseplant.opt.glb')
