/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/oscilloscope.glb -o src/scene/OscilloscopeModel.tsx -t -k 
Author: aonohono64 (https://sketchfab.com/aonohono64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laboratory-oscilloscope-20mhz-a8975bc6c48d440a896c57167cf58c80
Title: Laboratory Oscilloscope 20MHz
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import IntrinsicElements = React.JSX.IntrinsicElements;

type GLTFResult = GLTF & {
  nodes: {
    Cube001_Material_0: THREE.Mesh
    Cube002_Material095_0: THREE.Mesh
    Grid_Material106_0: THREE.Mesh
    Grid001_Material107_0: THREE.Mesh
    Cylinder_Material103_0: THREE.Mesh
    Cylinder001_Material098_0: THREE.Mesh
    Cube_Material127_0: THREE.Mesh
    Cylinder002_Material131_0: THREE.Mesh
    Cylinder003_Material132_0: THREE.Mesh
    Cylinder004_Material133_0: THREE.Mesh
    Cylinder005_Material123_0: THREE.Mesh
    Cylinder006_Material124_0: THREE.Mesh
    Cylinder007_Material117_0: THREE.Mesh
    Cylinder008_Material118_0: THREE.Mesh
    Cylinder009_Material105_0: THREE.Mesh
    Cube003_Material129_0: THREE.Mesh
    Cylinder010_Material135_0: THREE.Mesh
    Cylinder012_Material121_0: THREE.Mesh
    Cylinder013_Material122_0: THREE.Mesh
    Grid002_Material108_0: THREE.Mesh
    Cylinder016_Material104_0: THREE.Mesh
    Cube004_Material128_0: THREE.Mesh
    Cylinder017_Material115_0: THREE.Mesh
    Cylinder018_Material116_0: THREE.Mesh
    Cylinder019_Material145_0: THREE.Mesh
    Cylinder020_Material146_0: THREE.Mesh
    Cylinder021_Material147_0: THREE.Mesh
    Grid003_Material157_0: THREE.Mesh
    Cylinder022_Material148_0: THREE.Mesh
    Grid004_Material158_0: THREE.Mesh
    Grid005_Material109_0: THREE.Mesh
    Cylinder023_Material149_0: THREE.Mesh
    Grid006_Material152_0: THREE.Mesh
    Cube005_Material140_0: THREE.Mesh
    Cube006_Material141_0: THREE.Mesh
    Cube007_Material153_0: THREE.Mesh
    Cube008_Material154_0: THREE.Mesh
    Cylinder024_Material151_0: THREE.Mesh
    Grid007_Material156_0: THREE.Mesh
    Cylinder025_Material150_0: THREE.Mesh
    Grid008_Material155_0: THREE.Mesh
    Cube009_Material139_0: THREE.Mesh
    Cube010_Material138_0: THREE.Mesh
    Cube011_Material142_0: THREE.Mesh
    Grid009_Material114_0: THREE.Mesh
    Grid011_Material144_0: THREE.Mesh
    Grid012_Material113_0: THREE.Mesh
    Grid010_Material143_0: THREE.Mesh
    Grid013_Material110_0: THREE.Mesh
    Grid014_Material112_0: THREE.Mesh
    Grid015_Material111_0: THREE.Mesh
    Cylinder011_Material134_0: THREE.Mesh
    Cylinder014_Material137_0: THREE.Mesh
    Cylinder015_Material136_0: THREE.Mesh
    Sphere_Material125_0: THREE.Mesh
    Sphere001_Material130_0: THREE.Mesh
    Cube012_Material102_0: THREE.Mesh
    Text_Material001_0: THREE.Mesh
    Cube013_Material096_0: THREE.Mesh
    Text001_Material002_0: THREE.Mesh
    Text002_Material003_0: THREE.Mesh
    Text003_Material004_0: THREE.Mesh
    Text004_Material005_0: THREE.Mesh
    Text005_Material006_0: THREE.Mesh
    Text006_Material007_0: THREE.Mesh
    Text007_Material008_0: THREE.Mesh
    Text008_Material009_0: THREE.Mesh
    Text009_Material010_0: THREE.Mesh
    Text010_Material011_0: THREE.Mesh
    Text011_Material012_0: THREE.Mesh
    Text012_Material013_0: THREE.Mesh
    Text013_Material014_0: THREE.Mesh
    Text014_Material015_0: THREE.Mesh
    Text015_Material016_0: THREE.Mesh
    Text016_Material017_0: THREE.Mesh
    Text017_Material019_0: THREE.Mesh
    Text018_Material065_0: THREE.Mesh
    Text019_Material066_0: THREE.Mesh
    Text020_Material067_0: THREE.Mesh
    Text021_Material068_0: THREE.Mesh
    Text022_Material069_0: THREE.Mesh
    Text023_Material070_0: THREE.Mesh
    Text024_Material071_0: THREE.Mesh
    Text025_Material072_0: THREE.Mesh
    Text026_Material073_0: THREE.Mesh
    Text027_Material074_0: THREE.Mesh
    Text028_Material075_0: THREE.Mesh
    Text029_Material076_0: THREE.Mesh
    Grid016_Material119_0: THREE.Mesh
    Text030_Material077_0: THREE.Mesh
    Text031_Material078_0: THREE.Mesh
    Text032_Material079_0: THREE.Mesh
    Text033_Material080_0: THREE.Mesh
    Text034_Material081_0: THREE.Mesh
    Text035_Material082_0: THREE.Mesh
    Text036_Material083_0: THREE.Mesh
    Text037_Material084_0: THREE.Mesh
    Text038_Material085_0: THREE.Mesh
    Text039_Material086_0: THREE.Mesh
    Text040_Material087_0: THREE.Mesh
    Text041_Material088_0: THREE.Mesh
    Text042_Material089_0: THREE.Mesh
    Grid017_Material120_0: THREE.Mesh
    Text043_Material090_0: THREE.Mesh
    Text044_Material091_0: THREE.Mesh
    Text045_Material092_0: THREE.Mesh
    Text046_Material093_0: THREE.Mesh
    Text047_Material094_0: THREE.Mesh
    Cube014_Material097_0: THREE.Mesh
    Cylinder026_Material099_0: THREE.Mesh
    Cylinder027_Material100_0: THREE.Mesh
    Cylinder028_Material101_0: THREE.Mesh
    Sphere013_Material034_0: THREE.Mesh
    Sphere002_Material034_0: THREE.Mesh
    Sphere003_Material034_0: THREE.Mesh
    Sphere004_Material034_0: THREE.Mesh
    Sphere005_Material034_0: THREE.Mesh
    Sphere006_Material034_0: THREE.Mesh
    Sphere007_Material034_0: THREE.Mesh
    Sphere008_Material034_0: THREE.Mesh
    Cube015_Material126_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.095']: THREE.MeshStandardMaterial
    ['Material.108']: THREE.MeshStandardMaterial
    ['Material.103']: THREE.MeshStandardMaterial
    ['Material.100']: THREE.MeshStandardMaterial
    ['Material.128']: THREE.MeshStandardMaterial
    ['Material.121']: THREE.MeshStandardMaterial
    ['Material.124']: THREE.MeshStandardMaterial
    ['Material.129']: THREE.MeshStandardMaterial
    ['Material.137']: THREE.MeshStandardMaterial
    ['Material.145']: THREE.MeshStandardMaterial
    ['Material.073']: THREE.MeshStandardMaterial
    ['Material.138']: THREE.MeshStandardMaterial
    ['Material.110']: THREE.MeshStandardMaterial
    ['Material.125']: THREE.MeshStandardMaterial
    ['Material.102']: THREE.MeshStandardMaterial
    ['Material.119']: THREE.MeshStandardMaterial
    ['Material.120']: THREE.MeshStandardMaterial
    ['Material.101']: THREE.MeshStandardMaterial
    ['Material.126']: THREE.MeshStandardMaterial
  }
}

export function Model(props: IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/oscilloscope.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="db0353bc762d4ae7bc227df01fee1c17fbx" scale={0.01}>
        <mesh name="Cube001_Material_0" geometry={nodes.Cube001_Material_0.geometry} material={materials.Material} position={[-256.792, 538.823, 606.015]} rotation={[-1.714, 0, 0]} scale={[215.317, 20.563, 193.227]} />
        <mesh name="Cube002_Material095_0" geometry={nodes.Cube002_Material095_0.geometry} material={materials['Material.095']} position={[27.188, 424.631, 14.529]} rotation={[-1.714, 0, 0]} scale={[528.647, 602.408, 254.991]} />
        <mesh name="Grid_Material106_0" geometry={nodes.Grid_Material106_0.geometry} material={materials['Material.108']} position={[92.719, 510.71, 601.151]} rotation={[-0.143, 0, 0]} scale={[117.48, 5.022, 100]} />
        <mesh name="Grid001_Material107_0" geometry={nodes.Grid001_Material107_0.geometry} material={materials['Material.108']} position={[414.737, 510.71, 601.151]} rotation={[-0.143, 0, 0]} scale={[117.48, 5.022, 100]} />
        <mesh name="Cylinder_Material103_0" geometry={nodes.Cylinder_Material103_0.geometry} material={materials['Material.103']} position={[234.657, 598.876, 634.345]} rotation={[-0.142, 0, 0]} scale={52.828} />
        <mesh name="Cylinder001_Material098_0" geometry={nodes.Cylinder001_Material098_0.geometry} material={materials['Material.100']} position={[567.091, 478.203, 257.637]} rotation={[1.085, 1.569, -1.228]} scale={[62.457, 62.457, 20.078]} />
        <mesh name="Cube_Material127_0" geometry={nodes.Cube_Material127_0.geometry} material={materials['Material.128']} position={[263.281, 613.6, 667.204]} rotation={[-1.714, -0.215, 0]} scale={[19.907, 19.907, 5.415]} />
        <mesh name="Cylinder002_Material131_0" geometry={nodes.Cylinder002_Material131_0.geometry} material={materials['Material.103']} position={[131.008, 578.459, 601.401]} rotation={[-0.142, 0, 0]} scale={[13.183, 13.183, 23.459]} />
        <mesh name="Cylinder003_Material132_0" geometry={nodes.Cylinder003_Material132_0.geometry} material={materials['Material.103']} position={[32.054, 578.459, 601.401]} rotation={[-0.142, 0, 0]} scale={[13.183, 13.183, 23.459]} />
        <mesh name="Cylinder004_Material133_0" geometry={nodes.Cylinder004_Material133_0.geometry} material={materials['Material.103']} position={[362.513, 578.459, 601.401]} rotation={[-0.142, 0, 0]} scale={[13.183, 13.183, 23.459]} />
        <mesh name="Cylinder005_Material123_0" geometry={nodes.Cylinder005_Material123_0.geometry} material={materials['Material.121']} position={[466.763, 567.18, 603.031]} rotation={[-0.142, 0, 0]} scale={[18.677, 18.677, 33.236]} />
        <mesh name="Cylinder006_Material124_0" geometry={nodes.Cylinder006_Material124_0.geometry} material={materials['Material.124']} position={[466.763, 567.916, 608.128]} rotation={[2.997, 0.001, -Math.PI]} scale={[6.551, 6.551, 25.035]} />
        <mesh name="Cylinder007_Material117_0" geometry={nodes.Cylinder007_Material117_0.geometry} material={materials['Material.121']} position={[466.763, 306.467, 640.712]} rotation={[-0.142, 0, 0]} scale={[18.677, 18.677, 33.236]} />
        <mesh name="Cylinder008_Material118_0" geometry={nodes.Cylinder008_Material118_0.geometry} material={materials['Material.124']} position={[466.763, 307.203, 645.809]} rotation={[2.997, 0.001, -Math.PI]} scale={[6.551, 6.551, 25.035]} />
        <mesh name="Cylinder009_Material105_0" geometry={nodes.Cylinder009_Material105_0.geometry} material={materials['Material.103']} position={[59.89, 433.506, 657.44]} rotation={[-0.142, 0, 0]} scale={42.462} />
        <mesh name="Cube003_Material129_0" geometry={nodes.Cube003_Material129_0.geometry} material={materials['Material.129']} position={[72.884, 457.427, 682.105]} rotation={[-1.714, -1.093, 0]} scale={[16.001, 16.001, 4.352]} />
        <mesh name="Cylinder010_Material135_0" geometry={nodes.Cylinder010_Material135_0.geometry} material={materials['Material.137']} position={[167.497, 441.408, 621.209]} rotation={[-0.142, 0, 0]} scale={[13.183, 13.183, 23.459]} />
        <mesh name="Cylinder012_Material121_0" geometry={nodes.Cylinder012_Material121_0.geometry} material={materials['Material.121']} position={[297.719, 306.467, 640.712]} rotation={[-0.142, 0, 0]} scale={[13.716, 13.716, 24.408]} />
        <mesh name="Cylinder013_Material122_0" geometry={nodes.Cylinder013_Material122_0.geometry} material={materials['Material.124']} position={[297.719, 305.182, 631.822]} rotation={[2.997, 0.001, -Math.PI]} scale={[8.102, 8.102, 30.964]} />
        <mesh name="Grid002_Material108_0" geometry={nodes.Grid002_Material108_0.geometry} material={materials['Material.108']} position={[255.054, 474.808, 606.34]} rotation={[-0.144, -0.001, -1.571]} scale={[27.05, 0.875, 100]} />
        <mesh name="Cylinder016_Material104_0" geometry={nodes.Cylinder016_Material104_0.geometry} material={materials['Material.103']} position={[439.61, 433.506, 657.44]} rotation={[-0.142, 0, 0]} scale={42.462} />
        <mesh name="Cube004_Material128_0" geometry={nodes.Cube004_Material128_0.geometry} material={materials['Material.128']} position={[462.62, 440.561, 684.543]} rotation={[-1.714, -0.007, 0]} scale={[16.001, 16.001, 4.352]} />
        <mesh name="Cylinder017_Material115_0" geometry={nodes.Cylinder017_Material115_0.geometry} material={materials['Material.121']} position={[28.423, 306.467, 640.712]} rotation={[-0.142, 0, 0]} scale={[18.677, 18.677, 33.236]} />
        <mesh name="Cylinder018_Material116_0" geometry={nodes.Cylinder018_Material116_0.geometry} material={materials['Material.124']} position={[28.423, 307.203, 645.809]} rotation={[2.997, 0.001, -Math.PI]} scale={[6.551, 6.551, 25.035]} />
        <mesh name="Cylinder019_Material145_0" geometry={nodes.Cylinder019_Material145_0.geometry} material={materials['Material.145']} position={[-302.361, 307.283, 656.461]} rotation={[-0.142, 0, 0]} scale={[13.183, 13.183, 23.459]} />
        <mesh name="Cylinder020_Material146_0" geometry={nodes.Cylinder020_Material146_0.geometry} material={materials['Material.145']} position={[-404.578, 307.283, 656.461]} rotation={[-0.142, 0, 0]} scale={[13.183, 13.183, 23.459]} />
        <mesh name="Cylinder021_Material147_0" geometry={nodes.Cylinder021_Material147_0.geometry} material={materials['Material.103']} position={[418.786, 680.755, 585.281]} rotation={[-1.714, 0, 0]} scale={[17.595, 17.595, 6.508]} />
        <mesh name="Grid003_Material157_0" geometry={nodes.Grid003_Material157_0.geometry} material={materials['Material.073']} position={[418.247, 647.993, 582.797]} rotation={[-0.144, -0.001, -1.571]} scale={[27.842, 3.556, 70.819]} />
        <mesh name="Cylinder022_Material148_0" geometry={nodes.Cylinder022_Material148_0.geometry} material={materials['Material.103']} position={[477.145, 680.755, 585.281]} rotation={[-1.714, 0, 0]} scale={[17.595, 17.595, 6.508]} />
        <mesh name="Grid004_Material158_0" geometry={nodes.Grid004_Material158_0.geometry} material={materials['Material.073']} position={[476.606, 647.993, 582.797]} rotation={[-0.144, -0.001, -1.571]} scale={[27.842, 3.556, 70.819]} />
        <mesh name="Grid005_Material109_0" geometry={nodes.Grid005_Material109_0.geometry} material={materials['Material.108']} position={[255.054, 309.986, 630.162]} rotation={[-0.144, -0.001, -1.571]} scale={[28.89, 0.875, 100]} />
        <mesh name="Cylinder023_Material149_0" geometry={nodes.Cylinder023_Material149_0.geometry} material={materials['Material.103']} position={[256.884, 357.274, 633.521]} rotation={[-1.714, 0, 0]} scale={[19.041, 18.65, 9.189]} />
        <mesh name="Grid006_Material152_0" geometry={nodes.Grid006_Material152_0.geometry} material={materials['Material.073']} position={[255.619, 380.342, 619.993]} rotation={[-0.144, -0.001, -1.571]} scale={[39.315, 5.022, 100]} />
        <mesh name="Cube005_Material140_0" geometry={nodes.Cube005_Material140_0.geometry} material={materials['Material.073']} position={[81.481, 547.677, 590.233]} rotation={[-1.714, 0, 0]} scale={[10.674, 10.674, 7.439]} />
        <mesh name="Cube006_Material141_0" geometry={nodes.Cube006_Material141_0.geometry} material={materials['Material.073']} position={[410.619, 547.677, 590.233]} rotation={[-1.714, 0, 0]} scale={[10.674, 10.674, 7.439]} />
        <mesh name="Cube007_Material153_0" geometry={nodes.Cube007_Material153_0.geometry} material={materials['Material.073']} position={[194.336, 390.512, 619.101]} rotation={[-1.714, 0, 0]} scale={[12.817, 12.817, 8.932]} />
        <mesh name="Cube008_Material154_0" geometry={nodes.Cube008_Material154_0.geometry} material={materials['Material.073']} position={[315.494, 390.512, 619.101]} rotation={[-1.714, 0, 0]} scale={[12.817, 12.817, 8.932]} />
        <mesh name="Cylinder024_Material151_0" geometry={nodes.Cylinder024_Material151_0.geometry} material={materials['Material.103']} position={[108.308, 349.624, 634.066]} rotation={[-1.714, 0, 0]} scale={[22.109, 22.109, 8.177]} />
        <mesh name="Grid007_Material156_0" geometry={nodes.Grid007_Material156_0.geometry} material={materials['Material.073']} position={[107.183, 326.649, 628.315]} rotation={[-0.144, -0.001, -1.571]} scale={[34.986, 4.469, 88.99]} />
        <mesh name="Cylinder025_Material150_0" geometry={nodes.Cylinder025_Material150_0.geometry} material={materials['Material.103']} position={[392.297, 313.166, 639.261]} rotation={[-1.714, 0, 0]} scale={[21.75, 21.75, 8.045]} />
        <mesh name="Grid008_Material155_0" geometry={nodes.Grid008_Material155_0.geometry} material={materials['Material.073']} position={[391.19, 326.836, 628.362]} rotation={[-0.144, -0.001, -1.571]} scale={[34.418, 4.396, 87.544]} />
        <mesh name="Cube009_Material139_0" geometry={nodes.Cube009_Material139_0.geometry} material={materials['Material.073']} position={[-84.783, 318.62, 639.212]} rotation={[-1.714, 0, 0]} scale={[23.831, 14.076, 9.81]} />
        <mesh name="Cube010_Material138_0" geometry={nodes.Cube010_Material138_0.geometry} material={materials['Material.138']} position={[-84.783, 319.531, 645.518]} rotation={[-1.714, 0, 0]} scale={[21.604, 12.761, 8.893]} />
        <mesh name="Cube011_Material142_0" geometry={nodes.Cube011_Material142_0.geometry} material={materials['Material.073']} position={[353.023, 677.997, 571.397]} rotation={[-1.714, 0, 0]} scale={[10.674, 10.674, 7.439]} />
        <mesh name="Grid009_Material114_0" geometry={nodes.Grid009_Material114_0.geometry} material={materials['Material.108']} position={[510, 398.533, 617.364]} rotation={[-0.144, -0.001, -1.571]} scale={[-117.412, 0.875, 100]} />
        <mesh name="Grid011_Material144_0" geometry={nodes.Grid011_Material144_0.geometry} material={materials['Material.110']} position={[480.676, 712.096, 572.337]} rotation={[-0.143, 0, 0]} scale={[29.114, 5.022, 100]} />
        <mesh name="Grid012_Material113_0" geometry={nodes.Grid012_Material113_0.geometry} material={materials['Material.108']} position={[510, 601.381, 588.046]} rotation={[-0.144, -0.001, -1.571]} scale={[-117.412, 0.875, 100]} />
        <mesh name="Grid010_Material143_0" geometry={nodes.Grid010_Material143_0.geometry} material={materials['Material.110']} position={[365.149, 712.096, 572.337]} rotation={[-0.143, 0, 0]} scale={[29.114, 5.022, 100]} />
        <mesh name="Grid013_Material110_0" geometry={nodes.Grid013_Material110_0.geometry} material={materials['Material.110']} position={[144.012, 706.74, 572.819]} rotation={[-0.143, 0, 0]} scale={[145.541, 20.678, 100]} />
        <mesh name="Grid014_Material112_0" geometry={nodes.Grid014_Material112_0.geometry} material={materials['Material.108']} position={[314.22, 622.204, 585.037]} rotation={[-0.144, -0.001, -1.571]} scale={[-76.074, 0.875, 100]} />
        <mesh name="Grid015_Material111_0" geometry={nodes.Grid015_Material111_0.geometry} material={materials['Material.108']} position={[301.248, 701.779, 573.828]} rotation={[-0.143, 0, 0]} scale={[12.21, 5.022, 100]} />
        <mesh name="Cylinder011_Material134_0" geometry={nodes.Cylinder011_Material134_0.geometry} material={materials['Material.137']} position={[207.281, 463.919, 617.956]} rotation={[-0.142, 0, 0]} scale={[13.183, 13.183, 23.459]} />
        <mesh name="Cylinder014_Material137_0" geometry={nodes.Cylinder014_Material137_0.geometry} material={materials['Material.137']} position={[336.077, 441.408, 621.209]} rotation={[-0.142, 0, 0]} scale={[13.183, 13.183, 23.459]} />
        <mesh name="Cylinder015_Material136_0" geometry={nodes.Cylinder015_Material136_0.geometry} material={materials['Material.137']} position={[300.471, 463.919, 617.956]} rotation={[-0.142, 0, 0]} scale={[13.183, 13.183, 23.459]} />
        <mesh name="Sphere_Material125_0" geometry={nodes.Sphere_Material125_0.geometry} material={materials['Material.125']} position={[-149.001, 297.991, 641.536]} rotation={[-1.714, 0, 0]} scale={5.944} />
        <mesh name="Sphere001_Material130_0" geometry={nodes.Sphere001_Material130_0.geometry} material={materials['Material.073']} position={[-240.465, 296.377, 641.769]} rotation={[-1.714, 0, 0]} scale={7.828} />
        <mesh name="Cube012_Material102_0" geometry={nodes.Cube012_Material102_0.geometry} material={materials['Material.102']} position={[-257.673, 534.901, 597.404]} rotation={[-1.714, 0, Math.PI]} scale={[-200.081, 11.358, 177.009]} />
        <mesh name="Text_Material001_0" geometry={nodes.Text_Material001_0.geometry} material={materials['Material.073']} position={[148.216, 697.038, 574.264]} rotation={[-0.142, 0, 0]} scale={17.356} />
        <mesh name="Cube013_Material096_0" geometry={nodes.Cube013_Material096_0.geometry} material={materials['Material.100']} position={[27.188, 503.403, 559.547]} rotation={[-1.714, 0, 0]} scale={[536.787, 25.503, 265.682]} />
        <mesh name="Text001_Material002_0" geometry={nodes.Text001_Material002_0.geometry} material={materials['Material.073']} position={[103.142, 614.273, 586.226]} rotation={[-0.142, 0, 0]} scale={12.334} />
        <mesh name="Text002_Material003_0" geometry={nodes.Text002_Material003_0.geometry} material={materials['Material.073']} position={[-3.265, 614.273, 586.226]} rotation={[-0.142, 0, 0]} scale={12.334} />
        <mesh name="Text003_Material004_0" geometry={nodes.Text003_Material004_0.geometry} material={materials['Material.073']} position={[205.599, 673.43, 577.676]} rotation={[-0.142, 0, 0]} scale={12.334} />
        <mesh name="Text004_Material005_0" geometry={nodes.Text004_Material005_0.geometry} material={materials['Material.073']} position={[397.662, 707.356, 572.772]} rotation={[-0.142, 0, 0]} scale={12.615} />
        <mesh name="Text005_Material006_0" geometry={nodes.Text005_Material006_0.geometry} material={materials['Material.073']} position={[60.2, 561.697, 593.825]} rotation={[-0.142, 0, 0]} scale={9.635} />
        <mesh name="Text006_Material007_0" geometry={nodes.Text006_Material007_0.geometry} material={materials['Material.073']} position={[347.407, 598.198, 588.549]} rotation={[-0.142, 0, 0]} scale={12.334} />
        <mesh name="Text007_Material008_0" geometry={nodes.Text007_Material008_0.geometry} material={materials['Material.073']} position={[446.564, 598.198, 588.549]} rotation={[-0.142, 0, 0]} scale={12.334} />
        <mesh name="Text008_Material009_0" geometry={nodes.Text008_Material009_0.geometry} material={materials['Material.073']} position={[328.507, 690.36, 575.229]} rotation={[-0.142, 0, 0]} scale={11.681} />
        <mesh name="Text009_Material010_0" geometry={nodes.Text009_Material010_0.geometry} material={materials['Material.073']} position={[402.756, 690.348, 575.231]} rotation={[-0.142, 0, 0]} scale={11.681} />
        <mesh name="Text010_Material011_0" geometry={nodes.Text010_Material011_0.geometry} material={materials['Material.073']} position={[457.585, 690.348, 575.231]} rotation={[-0.142, 0, 0]} scale={11.681} />
        <mesh name="Text011_Material012_0" geometry={nodes.Text011_Material012_0.geometry} material={materials['Material.073']} position={[395.353, 582.094, 590.877]} rotation={[-0.142, 0, 0]} scale={11.681} />
        <mesh name="Text012_Material013_0" geometry={nodes.Text012_Material013_0.geometry} material={materials['Material.073']} position={[31.72, 491.609, 603.955]} rotation={[-0.142, 0, 0]} scale={12.9} />
        <mesh name="Text013_Material014_0" geometry={nodes.Text013_Material014_0.geometry} material={materials['Material.073']} position={[408.353, 491.609, 603.955]} rotation={[-0.142, 0, 0]} scale={12.9} />
        <mesh name="Text014_Material015_0" geometry={nodes.Text014_Material015_0.geometry} material={materials['Material.073']} position={[237.215, 430.83, 612.739]} rotation={[-0.142, 0, 0]} scale={14.208} />
        <mesh name="Text015_Material016_0" geometry={nodes.Text015_Material016_0.geometry} material={materials['Material.073']} position={[140.588, 467.025, 607.508]} rotation={[-0.144, -0.001, -1.571]} scale={8.338} />
        <mesh name="Text016_Material017_0" geometry={nodes.Text016_Material017_0.geometry} material={materials['Material.073']} position={[146.443, 455.913, 609.114]} rotation={[-0.144, 0.001, 1.57]} scale={8.338} />
        <mesh name="Text017_Material019_0" geometry={nodes.Text017_Material019_0.geometry} material={materials['Material.073']} position={[148.542, 458.955, 608.674]} rotation={[-0.142, 0, 0]} scale={7.728} />
        <mesh name="Text018_Material065_0" geometry={nodes.Text018_Material065_0.geometry} material={materials['Material.073']} position={[198.611, 479.716, 605.674]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text019_Material066_0" geometry={nodes.Text019_Material066_0.geometry} material={materials['Material.073']} position={[291.61, 479.716, 605.674]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text020_Material067_0" geometry={nodes.Text020_Material067_0.geometry} material={materials['Material.073']} position={[356.664, 467.025, 607.508]} rotation={[-0.144, -0.001, -1.571]} scale={8.338} />
        <mesh name="Text021_Material068_0" geometry={nodes.Text021_Material068_0.geometry} material={materials['Material.073']} position={[362.519, 455.913, 609.114]} rotation={[-0.144, 0.001, 1.57]} scale={8.338} />
        <mesh name="Text022_Material069_0" geometry={nodes.Text022_Material069_0.geometry} material={materials['Material.073']} position={[320.844, 458.955, 608.674]} rotation={[-0.142, 0, 0]} scale={7.728} />
        <mesh name="Text023_Material070_0" geometry={nodes.Text023_Material070_0.geometry} material={materials['Material.073']} position={[407.258, 570.686, 592.526]} rotation={[-0.142, 0, 0]} scale={11.681} />
        <mesh name="Text024_Material071_0" geometry={nodes.Text024_Material071_0.geometry} material={materials['Material.073']} position={[408.638, 559.686, 594.115]} rotation={[-0.142, 0, 0]} scale={14.004} />
        <mesh name="Text025_Material072_0" geometry={nodes.Text025_Material072_0.geometry} material={materials['Material.073']} position={[15.699, 330.566, 627.231]} rotation={[-0.142, 0, 0]} scale={12.9} />
        <mesh name="Text026_Material073_0" geometry={nodes.Text026_Material073_0.geometry} material={materials['Material.073']} position={[452.983, 330.566, 627.231]} rotation={[-0.142, 0, 0]} scale={12.9} />
        <mesh name="Text027_Material074_0" geometry={nodes.Text027_Material074_0.geometry} material={materials['Material.073']} position={[-170.265, 311.722, 641.263]} rotation={[-0.142, 0, 0]} scale={12.9} />
        <mesh name="Text028_Material075_0" geometry={nodes.Text028_Material075_0.geometry} material={materials['Material.073']} position={[-324.581, 324.472, 639.42]} rotation={[-0.142, 0, 0]} scale={12.9} />
        <mesh name="Text029_Material076_0" geometry={nodes.Text029_Material076_0.geometry} material={materials['Material.073']} position={[-423.098, 324.472, 639.42]} rotation={[-0.142, 0, 0]} scale={12.9} />
        <mesh name="Grid016_Material119_0" geometry={nodes.Grid016_Material119_0.geometry} material={materials['Material.119']} position={[-258.131, 726.834, 598.746]} rotation={[-0.143, 0, 0]} scale={[174.96, 11.158, 100]} />
        <mesh name="Text030_Material077_0" geometry={nodes.Text030_Material077_0.geometry} material={materials['Material.073']} position={[183.668, 413.65, 615.222]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text031_Material078_0" geometry={nodes.Text031_Material078_0.geometry} material={materials['Material.073']} position={[183.668, 403.751, 616.653]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text032_Material079_0" geometry={nodes.Text032_Material079_0.geometry} material={materials['Material.073']} position={[297.937, 403.751, 616.653]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text033_Material080_0" geometry={nodes.Text033_Material080_0.geometry} material={materials['Material.073']} position={[127.371, 328.943, 627.465]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text034_Material081_0" geometry={nodes.Text034_Material081_0.geometry} material={materials['Material.073']} position={[127.371, 317.594, 629.105]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text035_Material082_0" geometry={nodes.Text035_Material082_0.geometry} material={materials['Material.073']} position={[127.371, 306.253, 630.744]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text036_Material083_0" geometry={nodes.Text036_Material083_0.geometry} material={materials['Material.073']} position={[348.629, 328.943, 627.465]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text037_Material084_0" geometry={nodes.Text037_Material084_0.geometry} material={materials['Material.073']} position={[348.629, 317.594, 629.105]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text038_Material085_0" geometry={nodes.Text038_Material085_0.geometry} material={materials['Material.073']} position={[348.629, 306.253, 630.744]} rotation={[-0.142, 0, 0]} scale={8.758} />
        <mesh name="Text039_Material086_0" geometry={nodes.Text039_Material086_0.geometry} material={materials['Material.073']} position={[-260.826, 317.369, 640.447]} rotation={[-0.142, 0, 0]} scale={9.539} />
        <mesh name="Text040_Material087_0" geometry={nodes.Text040_Material087_0.geometry} material={materials['Material.073']} position={[-419.288, 721.54, 599.814]} rotation={[-0.142, 0, 0]} scale={17.356} />
        <mesh name="Text041_Material088_0" geometry={nodes.Text041_Material088_0.geometry} material={materials['Material.073']} position={[-312.582, 721.54, 599.814]} rotation={[-0.142, 0, 0]} scale={13.577} />
        <mesh name="Text042_Material089_0" geometry={nodes.Text042_Material089_0.geometry} material={materials['Material.073']} position={[-203.204, 721.54, 599.814]} rotation={[-0.142, 0, 0]} scale={13.577} />
        <mesh name="Grid017_Material120_0" geometry={nodes.Grid017_Material120_0.geometry} material={materials['Material.120']} position={[-111.34, 726.873, 599.021]} rotation={[-0.143, 0, 0]} scale={[-19.461, 6.952, 100]} />
        <mesh name="Text043_Material090_0" geometry={nodes.Text043_Material090_0.geometry} material={materials['Material.073']} position={[-129.237, 721.54, 599.814]} rotation={[-0.142, 0, 0]} scale={12.499} />
        <mesh name="Text044_Material091_0" geometry={nodes.Text044_Material091_0.geometry} material={materials['Material.073']} position={[219.083, 400.511, 617.121]} rotation={[-0.142, 0, 0]} scale={8.033} />
        <mesh name="Text045_Material092_0" geometry={nodes.Text045_Material092_0.geometry} material={materials['Material.073']} position={[219.083, 390.101, 618.626]} rotation={[-0.142, 0, 0]} scale={8.033} />
        <mesh name="Text046_Material093_0" geometry={nodes.Text046_Material093_0.geometry} material={materials['Material.073']} position={[219.083, 379.699, 620.129]} rotation={[-0.142, 0, 0]} scale={8.033} />
        <mesh name="Text047_Material094_0" geometry={nodes.Text047_Material094_0.geometry} material={materials['Material.073']} position={[219.083, 370.372, 621.477]} rotation={[-0.142, 0, 0]} scale={8.033} />
        <mesh name="Cube014_Material097_0" geometry={nodes.Cube014_Material097_0.geometry} material={materials['Material.100']} position={[27.188, 297.222, 454.137]} rotation={[-2.408, 0, 0]} scale={[581.615, 27.486, 286.405]} />
        <mesh name="Cylinder026_Material099_0" geometry={nodes.Cylinder026_Material099_0.geometry} material={materials['Material.103']} position={[557.217, 478.203, 257.637]} rotation={[1.085, 1.569, -1.228]} scale={[71.708, 71.708, 4.384]} />
        <mesh name="Cylinder027_Material100_0" geometry={nodes.Cylinder027_Material100_0.geometry} material={materials['Material.100']} position={[-513.334, 478.203, 257.634]} rotation={[2.359, -1.569, 2.216]} scale={[62.457, 62.457, 20.078]} />
        <mesh name="Cylinder028_Material101_0" geometry={nodes.Cylinder028_Material101_0.geometry} material={materials['Material.101']} position={[-503.459, 478.203, 257.64]} rotation={[2.359, -1.569, 2.216]} scale={[71.708, 71.708, 4.384]} />
        <mesh name="Sphere013_Material034_0" geometry={nodes.Sphere013_Material034_0.geometry} material={materials['Material.128']} position={[555.175, 279.451, 542.26]} rotation={[0.003, 1.474, -2.248]} scale={[9.788, 9.204, 7.319]} />
        <mesh name="Sphere002_Material034_0" geometry={nodes.Sphere002_Material034_0.geometry} material={materials['Material.128']} position={[555.175, 215.94, 62.039]} rotation={[0.003, 1.474, -2.248]} scale={[9.788, 9.204, 7.319]} />
        <mesh name="Sphere003_Material034_0" geometry={nodes.Sphere003_Material034_0.geometry} material={materials['Material.128']} position={[555.175, 134.188, -496.487]} rotation={[0.003, 1.474, -2.248]} scale={[9.788, 9.204, 7.319]} />
        <mesh name="Sphere004_Material034_0" geometry={nodes.Sphere004_Material034_0.geometry} material={materials['Material.128']} position={[555.175, 349.134, -533.391]} rotation={[0.003, 1.474, -2.248]} scale={[9.788, 9.204, 7.319]} />
        <mesh name="Sphere005_Material034_0" geometry={nodes.Sphere005_Material034_0.geometry} material={materials['Material.128']} position={[-499.578, 122.137, -505.916]} rotation={[2.875, -1.479, 0.92]} scale={[9.788, 9.204, 7.319]} />
        <mesh name="Sphere006_Material034_0" geometry={nodes.Sphere006_Material034_0.geometry} material={materials['Material.128']} position={[-499.858, 198.828, -45.863]} rotation={[2.875, -1.479, 0.92]} scale={[9.788, 9.204, 7.319]} />
        <mesh name="Sphere007_Material034_0" geometry={nodes.Sphere007_Material034_0.geometry} material={materials['Material.128']} position={[-499.254, 280.468, 512.674]} rotation={[2.875, -1.479, 0.92]} scale={[9.788, 9.204, 7.319]} />
        <mesh name="Sphere008_Material034_0" geometry={nodes.Sphere008_Material034_0.geometry} material={materials['Material.128']} position={[-500.958, 343.465, -550.063]} rotation={[2.875, -1.479, 0.92]} scale={[9.788, 9.204, 7.319]} />
        <mesh name="Cube015_Material126_0" geometry={nodes.Cube015_Material126_0.geometry} material={materials['Material.126']} position={[11.618, 112.05, 663.182]} rotation={[-0.805, 0, 0]} scale={[146.859, 34.171, 34.329]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/oscilloscope.glb')
